blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls',namespace = 'blogs')),
    path('users/',include('users.urls',namespace = 'users'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path

from . import views

urlpatterns = [
#Home page
path('',views.index,name = 'index'),
#Page with the list of posts
path('posts',views.posts,name = 'posts'),
#Page with details for every post
path('post/<int:post_id>',views.post,name = 'post'),
#Ability that add post
path('add_post',views.add_post,name = 'add_post'),
#Ability to change text of post
path('edit_post/<int:post_id>',views.edit_post,name = 'edit_post')
]

app_name = 'blogs'

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
from blogs.decorators import unauthenticated_user

urlpatterns = [ 
#Login page
path('login', unauthenticated_user(LoginView.as_view(template_name = 'users/login.html')),name = 'login'),
#Logout page
path('logout',views.logout_view, name = 'logout'),
#Sign up page
path('register',views.register,name = 'register'),
]

app_name = 'users'

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class BlogPost(models.Model):
	title = models.CharField(max_length = 200)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add = True)
	date_edit = models.DateTimeField(auto_now = True)
	image = models.ImageField(upload_to = 'images',blank = True)
	owner = models.ForeignKey(User,on_delete = models.DO_NOTHING)

	def __str__(self):
		return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogPostForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields = ['title']
		labels = {'text':''}

class EditPostForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields = ['text']
		labels = {'text':''}

blogs/views.py
from django.shortcuts import render 
from django.urls import reverse
from django.http import HttpResponseRedirect,Http404


from .forms import BlogPostForm,EditPostForm
from .models import BlogPost
from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .decorators import allowed_user
from .author_check import checking_author
from .own_classes import OwnPaginator

def index(request):
	return render(request,'blogs/index.html')


def posts(request):
	posts = BlogPost.objects.order_by('-date_added')[:10]
	context = {'posts':posts}
	return render (request,'blogs/posts.html',context)
 

def post(request,post_id):
	post = BlogPost.objects.get(id = post_id)
	
	#OwnPaginator take 2 args:model name(model_name) and post id(p_id)
	pag = OwnPaginator(BlogPost,post_id)

	next_post = pag.show_next_post()
	previous_post = pag.show_previous_post()

	post_text = post.text
	username = post.owner
	context = {
		'post':post,
		'post_text':post_text,
		'username':username,
		'previous_post':previous_post,
		'next_post':next_post
	}
	return render (request,'blogs/post.html',context)


@login_required
@allowed_user(allowed_roles=['admins'])
def add_post(request):
	if request.method !='POST':
		form = BlogPostForm()
	else:
		form = BlogPostForm(request.POST)
		if form.is_valid():
			new_post = form.save(commit = False)
			new_post.owner = request.user
			new_post.save()
			return HttpResponseRedirect(reverse('blogs:posts'))
	context = {'form':form}
	return render (request,'blogs/add_post.html',context)


@login_required
@allowed_user(allowed_roles=['admins'])
def edit_post(request,post_id):
	post = BlogPost.objects.get(id = post_id)
	post_text = post.text
	title = post.title
	checking_author(request,post_id)
	if request.method != 'POST':
		form = EditPostForm(instance = post)
	else:
		form = EditPostForm(instance = post,data = request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('blogs:post',args = [post.id]))

	context = {'post':post,'post_text':post_text,'form':form}
	return render (request,'blogs/edit_post.html',context)

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse 
from django.http import HttpResponseRedirect
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.models import Group

from blogs.decorators import unauthenticated_user
# Create your views here.

def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('users:login'))

@unauthenticated_user
def register(request):
	#Creating a registration page
	if request.method != 'POST':
		#Registration form
		form = UserCreationForm()
	else:
		form = UserCreationForm(request.POST)
		if form.is_valid():
			new_user = form.save()

			group = Group.objects.get(name='customer')
			new_user.groups.add(group)

			#Redirect to homepage
			auth_user = authenticate(username = new_user.username,password = request.POST['password1'])
			login(request,auth_user)
			return HttpResponseRedirect(reverse('blogs:index'))

	context = {'form':form}

	return render(request,'users/register.html',context)

blogs/templates/blogs/add_post.html
{%extends 'blogs/base.html'%}
{% load bootstrap3 %}

{% block header %}
<h2>
	Add a new post:	
</h2>
{% endblock %}

{% block content %}

<form action = "{% url 'blogs:add_post'%}" method="post" class="form">
	{%csrf_token%}
	{% bootstrap_form form%}

	{% buttons %}
	<button name = 'submit'>add this post</button>
	{% endbuttons %}
</form>

{%endblock content%}

blogs/templates/blogs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compratible" content='IE=edge'>
	<meta name='viewport' content="width=device-width,initial-scale=1">
	
	<title>Blog</title>

	{% bootstrap_css %}
	{% bootstrap_javascript %}
</head>
<body>
	<!--STATIC NAVIGATION MODEL-->
	<nav class='navbar navbar-default navbar-static top'>
		<div class='container'>
			<div class='navbar-header'>
				<button type='button' class='navbar-toggle collapsed'
					data-toggle='collapse' data-target='#navbar'
					aria-expended='false' aria-controls='navbar'>					
				</button>
				<a class='navbar-brand' href = '{% url "blogs:index" %}'>Homepage</a>
			</div>
			<div id='navbar' class='navbar-collapse collapse'>
				<ul class='nav navbar-nav'>
					<li><a href="{% url 'blogs:posts' %}">Blog</a></li>
					{% if request.user.is_staff %}
					<li><a href="{% url 'admin:index'%}">Admin</a></li>
					{% endif %}
				</ul>
				<ul class='nav navbar-nav navbar-right'>
					{% if user.is_authenticated %}
					<li>Hello,{{user.username}}</a></li>
					<li><a href="{% url 'users:logout' %}">Logout</a></li>
					{% else %}
					<li><a href="{% url 'users:login' %}">Log in</a></li>
					<li><a href="{% url 'users:register' %}">Sign up</a></li>
					{% endif %}
				</ul>
			</div><!--/.nav-collapse-->
		</div>
	</nav>
	<div class='container'>
		<div class='page-header'>
			{% block header%} {% endblock header %}
		</div>
		<div>
			{% block content%} {% endblock content %}
		</div>
	</div><!--container-->
</body>
</html>

blogs/templates/blogs/edit_post.html
{%extends 'blogs/base.html'%}
{% load bootstrap3 %}

{% block header %}
<h2>
	Changing post:
</h2>
{% endblock header %}

{%block content%}

<form action="{% url 'blogs:edit_post' post.id%}" method = 'post' class='form'>
	{%csrf_token%}
	{% bootstrap_form form %}

	{% buttons %}
	<button name = 'submit'>save changes</button>
	{% endbuttons %}
	
</form>

{%endblock content%}

blogs/templates/blogs/index.html
{%extends 'blogs/base.html'%}
{% load bootstrap3 %}

{% block header%}
<h1>
	<center>This is a simple blog for your entries.</center>
</h1>
{% endblock header %}

{%block content%}

<h2>
	<center><a href="{% url 'users:register' %}">Sign up </a>and try it now</center>
</h2>

{%endblock content%}

blogs/templates/blogs/post.html
{%extends 'blogs/base.html'%}


{% block header %}
<ul class='pagination'>
	<li class="page-item">
		{% if previous_post %}
		<a class ='page-link' href="{% url 'blogs:post' previous_post.id %}">Previous</a>
		{% endif %}
	</li>
	
	<li class="page-item">
		{% if next_post %}
		<a class ='page-link' href="{% url 'blogs:post' next_post.id %}">Next</a>
		{% endif %}
	</li>
</ul>
<h2>
	{{post}}:	
</h2>
{% endblock header %}

{%block content%}
<div class="panel panel-default">
<div class='panel-body'>
	<h4>
		{{post_text}}
		{% if post.image %}
			<p><center><img src="{{ post.image.url }}" width="240"></center></p>
		{% endif %}
	</h4>
</div>
	<div class="panel-heading">
		Published:{{post.date_added|date:'d M,Y H:m'}} . Edit:{{post.date_edit|date:'d M,Y H:m'}} . Author:{{username}}
	</div>
</div>
<p></p>
<div><a href="{% url 'blogs:edit_post' post.id%}">add/edit entry</a></div>



{%endblock content%}

blogs/templates/blogs/posts.html
{%extends 'blogs/base.html'%}
{% load bootstrap3 %}

{% block header %}
<h2>
	Entries
</h2>
{% endblock header %}

{%block content%}

{%for post in posts%}
<ul>
	<h4>
		<li><a href="{% url 'blogs:post' post.id %}">{{post}}</a></li>
	</h4>
</ul>
{%empty%}
<p>no posts available right now,sorry:(</p>
{%endfor%}

<h4><a href = "{% url 'blogs:add_post'%}">add post</a></h4>

{%endblock content%}

users/templates/users/login.html
{% extends 'blogs/base.html'%}
{% load bootstrap3 %}

{% block header %}
<h2>
	Authentication
</h2>
{% endblock header %}

{%block content %}

<form action = "{% url 'users:login' %}" method = 'post' class="form">
	{%csrf_token%}
	{% bootstrap_form form %}

	{% buttons %}
	<button name = 'submit'>Log in</button>
	{% endbuttons %}
<input type="hidden" name="next" value = "{% url 'blogs:index' %}">

</form>
{%endblock content%}

users/templates/users/register.html
{%extends 'blogs/base.html'%}
{% load bootstrap3 %}

{% block header %}
<h2>
	Registration
</h2>
{% endblock header %}

{%block content%}

<form action="{% url 'users:register'%}" method="post" class="form">
	{%csrf_token%}
	{% bootstrap_form form %}
	
	{% buttons %}
	<button name = 'submit'>Register</button>
	<input type="hidden" name="next" value="{% url 'blogs:index'%}">
	{% endbuttons %}
</form>

{%endblock content%}